[package]
name = "palel"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
pest = "2.8.1"
pest_derive = "2.8.1"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1"
